apiVersion: v1
kind: ConfigMap
metadata:
  name: rger-config
data:
  ENV: "prod"
  LOG_LEVEL: "info"
  AWS_REGION: "us-west-2"
  S3_BUCKET: "your-app-bucket"
  # Add other non-sensitive configuration here