apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: your-app
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "your-app/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
          - path: "host"
            objectAlias: "db-host"
          - path: "port"
            objectAlias: "db-port"
      - objectName: "your-app/api-keys"
        objectType: "secretsmanager"
        jmesPath:
          - path: "api_key"
            objectAlias: "api-key"
          - path: "secret_key"
            objectAlias: "secret-key"
  secretObjects:
    - secretName: app-database-secret
      type: Opaque
      data:
        - objectName: "db-username"
          key: "username"
        - objectName: "db-password"
          key: "password"
        - objectName: "db-host"
          key: "host"
        - objectName: "db-port"
          key: "port"
    - secretName: app-api-secret
      type: Opaque
      data:
        - objectName: "api-key"
          key: "api_key"
        - objectName: "secret-key"
          key: "secret_key"