apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/0E7E458DFA3D7DD8B8DFDD9041872D74