apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP  # This is correct when using Ingress
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: my-appapiVersion: v1
kind: Service
metadata:
  name: your-app-service
  namespace: your-app
  labels:
    app: your-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: your-app