apiVersion: v1
kind: Service
metadata:
  name: app-service  # ⭐ Key name referenced in Ingress
spec:
  selector:
    app: app          # Matches Deployment’s Pod labels
  ports:
    - protocol: TCP
      port: 80          # Service port (external)
      targetPort: 5000  # Pod port (internal)
  type: ClusterIP